text = {"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.":"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.",
        "belépsz és gyújtasz egy fáklyát":"belépsz és gyújtasz egy fáklyát",
        "besétálsz a sötétbe":"besétálsz a sötétbe",
        "Túl hideg van, halálra fagytál!":"Túl hideg van, halálra fagytál!",
        "újrakezdés":"újrakezdés",
        "kilépés":"kilépés",
        "Gyújtasz egy fáklyát. Balra van egy nyitott ajtó, de a fény nem hatol be. Jobbra egy zárt, rozoga ajtó.":"Gyújtasz egy fáklyát. Balra van egy nyitott ajtó, de a fény nem hatol be. Jobbra egy zárt, rozoga ajtó.",
        "Jobb oldali ajtó":"Jobb oldali ajtó",
        "Bal oldali ajtó":"Bal oldali ajtó",
        #Bal oldali ajtó
        "Besétálsz a nyitott szobába, a fáklyád nem ér semmit, ezért nem látsz és belesétálsz egy medvecsapdába.":"Besétálsz a nyitott szobába, a fáklyád nem ér semmit, ezért nem látsz és belesétálsz egy medvecsapdába.",
        #Jobb oldali ajtó
        "Megpróbálod kinyitni az ajtó. Nincs zárva, ezért lassan csikorogva kinyílik. Egy kobold van a szobában.":"Megpróbálod kinyitni az ajtó. Nincs zárva, ezért lassan csikorogva kinyílik. Egy kobold van a szobában.",
        "harc! (könnyű)":"harc! (könnyű)",
        "menekülés":"menekülés",
        "Gyáván megfutamodtál. A játék véget ért!":"Gyáván megfutamodtál. A játék véget ért!",
        "Nagyobbat dobtál mint az ellenfél, ezért csúnyán megverted!":"Nagyobbat dobtál mint az ellenfél, ezért csúnyán megverted!",
        "kifosztod":"kifosztod",
        "átvizsgálod a szobát":"átvizsgálod a szobát",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!":"Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!",
        "újrakezdés":"újrakezdés",
        "kilépés":"kilépés",
        "Átkutatod a koboldot. Találsz nála egy rozsdás kenőkést, és egy félig megevett zsíroskerenyeret. A rozsdás kenőkés szerencsét hoz!":"Átkutatod a koboldot. Találsz nála egy rozsdás kenőkést, és egy félig megevett zsíroskerenyeret. A rozsdás kenőkés szerencsét hoz!",
        "átvizsgálod a szobát":"átvizsgálod a szobát",
        "visszamész a folysóra":"visszamész a folysóra",
        "A folysó továbbra is üres. Most megfigyeled a végét, és látod hogy nincs folytatása.":"A folysó továbbra is üres. Most megfigyeled a végét, és látod hogy nincs folytatása.",
        "vissza a szobába":"vissza a szobába",
        "A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.":"A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.",        
        "Előttem lévő ajtó kinyitása":"Előttem lévő ajtó kinyitása",
        "jobb oldali ajtó kinyitása":"jobb oldali ajtó kinyitása",
        "Odasétálsz az ajtóhoz, és szerencsédre nyitva van":"Odasétálsz az ajtóhoz, és szerencsédre nyitva van",
        "bemész":"bemész",
        "másik ajtó megnézése":"másik ajtó megnézése",
        "A jobb oldali ajtó zárva van. Lehetetlen kinyitni.":"A jobb oldali ajtó zárva van. Lehetetlen kinyitni.",
        "vissza a másikhoz":"vissza a másikhoz",
        "Besétálsz az ajtón, és látsz egy kijáratot, fény szűrődik onnan. De egy hatalmas ork állja az utad.":"Besétálsz az ajtón, és látsz egy kijáratot, fény szűrődik onnan. De egy hatalmas ork állja az utad.",
        "Harcolsz vele(nehéz)":"Harcolsz vele(nehéz)",
        "megpróbálod megkerülni":"megpróbálod megkerülni",
        "megpróltál elfutni az ork mellett, és nagy szerencsédre sikkerel jártál és kijutottál a kazamatából":"megpróltál elfutni az ork mellett, és nagy szerencsédre sikkerel jártál és kijutottál a kazamatából",
        "játék újrakezdése":"játék újrakezdése",
        "kilépés":"kilépés",
        "Nagyobbat dobtál mint az ellenfél, ezért legyőzted és végre kijutottál a kazamatából":"Nagyobbat dobtál mint az ellenfél, ezért legyőzted és végre kijutottál a kazamatából",
        "játék újrakezdése":"játék újrakezdése",
        "kilépés":"kilépés",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán elfenekelt! Meghaltál!":"Kevesebbet dobtál mint az ellenfél, ezért csúnyán elfenekelt! Meghaltál!",
        "újrakezdés":"újrakezdés",
        "kilépés":"kilépés",}
        
        
        
