text = {"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.":"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.",
        "belépsz és gyyújtasz egy fáklyát":"",
        "besétálsz a sötétbe":"",
        "Túl hideg van, halálra fagytál!":"",
        "újrakezdés":"",
        "kilépés":"",
        "Gyújtasz egy fáklyát. Balra van egy nyitott ajtó, de a fény nem hatol be. Jobbra egy zárt, rozoga ajtó.":"",
        "Jobb oldali ajtó":"",
        "Bal oldali ajtó":"",
        #Bal oldali ajtó
        "Besétálsz a nyitott szobába, a fáklyád nem ér semmit, ezért nem látsz és belesétálsz egy medvecsapdába.":"",
        #Jobb oldali ajtó
        "Megpróbálod kinyitni az ajtó. Nincs zárva, ezért lassan csikorogva kinyílik. Egy kobold van a szobában.":"",
        "harc! (kockadobás)":"",
        "menekülés":"",
        "Gyáván megfutamodtál. A játék véget ért!":"",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!":"",
        "Nagyobbat dobtál mint az ellenfél, ezért csúnyán megverted!":"",
        "kifosztod":"",
        "átvizsgálod a szobát":"",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!":"",
        "újrakezdés":"",
        "kilépés":"",
        "Átkutatod a koboldot. Találsz nála egy rozsdás kenőkést, és egy félig megevett zsíroskerenyeret. A rozsdás kenőkés szerencsét hoz!":"",
        "átvizsgálod a szobát":"",
        "visszamész a folysóra":"",
        "A folysó továbbra is üres. Most megfigyeled a végét, és látod hogy nincs folytatása.":"",
        "vissza a szobába":"",
        "A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.":"A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.",        
        "Előttem lévő ajtó kinyitása":"Előttem lévő ajtó kinyitása",
        "jobb oldali ajtó kinyitása":"jobb oldali ajtó kinyitása",
        "Odasétálsz az ajtóhoz, és szerencsédre nyitva van":"Odasétálsz az ajtóhoz, és szerencsédre nyitva van",
        "bemész":"bemész",
        "másik ajtó megnézése":"másik ajtó megnézése",
        "A jobb oldali ajtó zárva van. Lehetetlen kinyitni.":"A jobb oldali ajtó zárva van. Lehetetlen kinyitni.",
        "vissza a másikhoz":"vissza a másikhoz",
        
