text = {"Sie gelangen zum Eingang des Verlieses. Die Tür öffnet sich knarrend und Sie werden von einem dunklen, muffigen Korridor begrüßt.":"Sie gelangen zum Eingang des Verlieses. Die Tür öffnet sich knarrend und Sie werden von einem dunklen, muffigen Korridor begrüßt.",
        "Du trittst ein und zündest eine Fackel an":"Du trittst ein und zündest eine Fackel an",
        "Du gehst in die Dunkelheit":"Du gehst in die Dunkelheit",
        "Es ist zu kalt, du frierst!":"Es ist zu kalt, du frierst!",
        "Neustart":"Neustart",
        "Ausfahrt":"Ausfahrt",
        "Du zündest eine Fackel an. Links ist eine offene Tür, aber das Licht dringt nicht ein. Rechts ist eine geschlossene, baufällige Tür.":"Du zündest eine Fackel an. Links ist eine offene Tür, aber das Licht dringt nicht ein. Rechts ist eine geschlossene, baufällige Tür.",
        "Tür rechts":"Tür rechts",
        "Tür links":"Tür links",
        "Wenn Sie ins Freie gehen, ist Ihre Taschenlampe wertlos, Sie können nichts sehen und laufen in eine Bärenfalle.":"Wenn Sie ins Freie gehen, ist Ihre Taschenlampe wertlos, Sie können nichts sehen und laufen in eine Bärenfalle.",
        "Du versuchst, die Tür zu öffnen. Es ist nicht geschlossen, daher klappt es langsam auf. Da ist ein Kobold im Raum.":"Du versuchst, die Tür zu öffnen. Es ist nicht geschlossen, daher klappt es langsam auf. Da ist ein Kobold im Raum.",
        "kämpfen! (einfach)":"kämpfen! (einfach)",
        "Flucht":"Flucht",
        "Du bist weggelaufen wie ein Feigling. Spiel vorbei!":"Du bist weggelaufen wie ein Feigling. Spiel vorbei!",
        "Du hast höher gewürfelt als dein Gegner, also hast du ihn schlecht geschlagen!":"Du hast höher gewürfelt als dein Gegner, also hast du ihn schlecht geschlagen!",
        "du plünderst":"du plünderst",
        "Du scannst den Raum":"Du scannst den Raum",
        "Du hast weniger gewürfelt als dein Gegner, also hat er dich schlecht geschlagen! Du bist tot!":"Du hast weniger gewürfelt als dein Gegner, also hat er dich schlecht geschlagen! Du bist tot!",
        "Neustart":"Neustart",
        "Ausfahrt":"Ausfahrt",
        "Du durchsuchst den Kobold. Sie finden ein rostiges Buttermesser und einen halb aufgegessenen Laib Fettbrot. Ein rostiges Buttermesser bringt Glück!":"Du durchsuchst den Kobold. Sie finden ein rostiges Buttermesser und einen halb aufgegessenen Laib Fettbrot. Ein rostiges Buttermesser bringt Glück!",
        "Du scannst den Raum":"Du scannst den Raum",
        "Du gehst zurück zum Flur":"Du gehst zurück zum Flur",
        "Der Flur ist noch leer. Jetzt beobachten Sie das Ende und sehen, dass es keine Fortsetzung gibt.":"Der Flur ist noch leer. Jetzt beobachten Sie das Ende und sehen, dass es keine Fortsetzung gibt.",
        "zurück ins Zimmer":"zurück ins Zimmer",
        "Der Raum wird von Ihrer Taschenlampe beleuchtet. Drinnen stehen ein Tisch und ein paar Stühle. Vor Ihnen und auf der rechten Seite befindet sich eine Tür.":"Der Raum wird von Ihrer Taschenlampe beleuchtet. Drinnen stehen ein Tisch und ein paar Stühle. Vor Ihnen und auf der rechten Seite befindet sich eine Tür.",
        "Öffne die Tür vor mir":"Öffne die Tür vor mir",
        "die Tür rechts öffnen":"die Tür rechts öffnen",
        "Du gehst zur Tür und zum Glück ist sie offen":"Du gehst zur Tür und zum Glück ist sie offen",
        "du gehst rein":"du gehst rein",
        "Blick auf eine andere Tür":"Blick auf eine andere Tür",
        "Die Tür rechts ist geschlossen. Unmöglich zu öffnen":"Die Tür rechts ist geschlossen. Unmöglich zu öffnen",
        "zurück zum anderen":"zurück zum anderen",
        "Du gehst durch die Tür und siehst einen Ausgang, aus dem Licht kommt. Aber ein riesiger Ork steht dir im Weg.":"Du gehst durch die Tür und siehst einen Ausgang, aus dem Licht kommt. Aber ein riesiger Ork steht dir im Weg.",
        "Du kämpfst dagegen (hart)":"Du kämpfst dagegen (hart)",
        "Du versuchst, es zu umgehen":"Du versuchst, es zu umgehen",
        "Du hast versucht, am Ork vorbeizulaufen und bist zum Glück aus dem Kerker herausgekommen":"Du hast versucht, am Ork vorbeizulaufen und bist zum Glück aus dem Kerker herausgekommen",
        "Spiel neustarten":"Spiel neustarten",
        "Ausfahrt":"Ausfahrt",
        "Du hast höher gewürfelt als dein Gegner, also hast du ihn geschlagen und bist schließlich aus dem Kerker herausgekommen.":"Du hast höher gewürfelt als dein Gegner, also hast du ihn geschlagen und bist schließlich aus dem Kerker herausgekommen.",
        "Spiel neustarten":"Spiel neustarten",
        "Ausfahrt":"Ausfahrt",
        "Du hast weniger gewürfelt als dein Gegner, also wurde er verprügelt! Du bist tot!":"Du hast weniger gewürfelt als dein Gegner, also wurde er verprügelt! Du bist tot!",
        "Spiel neustarten":"Spiel neustarten",
        "Ausfahrt":"Ausfahrt",}
